### PR TITLE
Functionality/recipe class

### LINKED ISSUE #6: Refactoring
Check for the following: 
- [x] Is the code following the SRP and is it dry? 
- [x] Are there any console Logs? 
- [x] Is there any commented out code or psuedoCode? 
- [x] make sure any events are listed as 'e' to be consistent
- [ ] are we using single or double quotes consistently (one type unless exception)
- [ ] bundle the recipeSection favorite/unfavorite and add to list 
- [ ] favorite / unfavorite icon should be the same on both the preview and the popout

### PR DESCRIPTION
**Pull request by angelewilliams**
# Description
This PR adds test and implementation code for the RecipeRepository class
## Issues
#1 
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring
# How Has This Been Tested?
- [ ] open localHost
- [ ] dev tools
- [x] TDD
# Checklist:
- [x] My code follows the Turing’s guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] No console error messages

### CODE REVIEW

File: src/classes/RecipeRepository.js [hunk 1]
```diff
@@ -1,7 +1,18 @@
 class RecipeRepository {
-  constructor() {
-
+  constructor(recipeData) {
+    this.recipeObjects = recipeData;
     // One class to get you started!
```
Comment (michaelputnam67) [inline src/classes/RecipeRepository.js:4]: Check for the following: 
- [x] Is the code following the SRP and is it dry? 
- [x] Are there any console Logs? 
- [x] Is there any commented out code or pseudocode?
